### ISSUE TITLE
Application crash after running a few minutes (socket hang up)

### ISSUE THREAD

**Issue by NicoNet** [Storj/storjshare-cli#163]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 6.0.1
Core:       3.0.4
Protocol:   0.8.0
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior

Application shouldn't crash.

### Actual Behavior

Crash.  Last several lines of log + error message.

```
{"level":"warn","message":"Contract no longer open to offers","timestamp":"2016-08-22T22:54:10.759Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"STORJ-CLUS-020.storj.space\",\"port\":4100,\"nodeID\":\"1a02769ee67b445ea2b0949f049fd4535629d574\",\"lastSeen\":1471906452579}","timestamp":"2016-08-22T22:54:12.579Z"}
{"level":"warn","message":"dropping received late response to 48d12362b8081e9072ef828f3dba905ed2137211","timestamp":"2016-08-22T22:54:12.612Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"server017.storj.dk\",\"port\":5617,\"nodeID\":\"4e87fb4dadd9cdb672d7b1cadc864985639daaf6\",\"lastSeen\":1471906452741}","timestamp":"2016-08-22T22:54:12.741Z"}
{"level":"info","message":"replying to message to b9988ade1ea795ba2991eed389fa23240a435f96","timestamp":"2016-08-22T22:54:12.770Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"STORJ-CLUS-020.storj.space\",\"port\":4100,\"nodeID\":\"1a02769ee67b445ea2b0949f049fd4535629d574\",\"lastSeen\":1471906452791}","timestamp":"2016-08-22T22:54:12.791Z"}
{"level":"warn","message":"dropping received late response to 64eb1ee475f28c4add93c3c33fc2d6373399e9cb","timestamp":"2016-08-22T22:54:12.816Z"}
{"level":"warn","message":"missing or empty reply from contact","timestamp":"2016-08-22T22:54:15.512Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"server017.storj.dk\",\"port\":5617,\"nodeID\":\"4e87fb4dadd9cdb672d7b1cadc864985639daaf6\",\"lastSeen\":1471906460589}","timestamp":"2016-08-22T22:54:20.590Z"}
{"level":"info","message":"replying to message to 3d161b8657c3115749fd55aa35e7307ae495f081","timestamp":"2016-08-22T22:54:20.623Z"}
{"type":"info","message":"telemetry report {\"storage\":{\"free\":161008812244,\"used\":52461356},\"bandwidth\":{\"upload\":2.23,\"download\":22.46},\"contact\":{\"protocol\":\"0.8.0\",\"address\":\"STORJ-CLUS-020.storj.space\",\"port\":4176,\"nodeID\":\"ce62ee6a0688a63787ef7520ba4def433ad42d13\",\"lastSeen\":1471906175785},\"payment\":\"18RZNu2nxTdeNyuDCwAMq8aBpgC3FFERPp\"}","timestamp":"2016-08-22T22:54:35.819Z"}
{"level":"warn","message":"rpc call 36ebbdc926b04b1d8b32d927f93a6bc6598bcc21 timed out","timestamp":"2016-08-22T22:54:36.219Z"}
{"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `36ebbdc926b04b1d8b32d927f93a6bc6598bcc21` timed out","timestamp":"2016-08-22T22:54:36.219Z"}
{"level":"warn","message":"could not locate renter for offer","timestamp":"2016-08-22T22:54:36.222Z"}
{"level":"warn","message":"rpc call 2110298e4a40bbf011346ab69c58c0eecde584ad timed out","timestamp":"2016-08-22T22:54:36.222Z"}
{"level":"info","message":"replying to message to daabc07999438f46b8e467f67339e613d8bb8d81","timestamp":"2016-08-22T22:54:36.223Z"}
{"level":"warn","message":"rpc call 4d3d56914d6c50e887cfd7e1f74a2c6e68b41a03 timed out","timestamp":"2016-08-22T22:54:36.244Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"STORJ-CLUS-020.storj.space\",\"port\":4100,\"nodeID\":\"1a02769ee67b445ea2b0949f049fd4535629d574\",\"lastSeen\":1471906484681}","timestamp":"2016-08-22T22:54:44.681Z"}
{"level":"warn","message":"dropping received late response to 4d3d56914d6c50e887cfd7e1f74a2c6e68b41a03","timestamp":"2016-08-22T22:54:44.713Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"server025.storj.dk\",\"port\":5025,\"nodeID\":\"49da99a6d6e78bab30092e47cf7e222c92f4d00e\",\"lastSeen\":1471906491079}","timestamp":"2016-08-22T22:54:51.079Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"server021.storj.dk\",\"port\":5921,\"nodeID\":\"cf5a9c4aa7a72ecb57cf3cb15244d1b18d5fad87\",\"lastSeen\":1471906510051}","timestamp":"2016-08-22T22:55:10.051Z"}
{"level":"error","message":"Message signature expired","timestamp":"2016-08-22T22:55:10.052Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"server021.storj.dk\",\"port\":5921,\"nodeID\":\"cf5a9c4aa7a72ecb57cf3cb15244d1b18d5fad87\",\"lastSeen\":1471906511393}","timestamp":"2016-08-22T22:55:11.393Z"}
{"level":"error","message":"Message signature expired","timestamp":"2016-08-22T22:55:11.395Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"STORJ-CLUS-020.storj.space\",\"port\":4100,\"nodeID\":\"1a02769ee67b445ea2b0949f049fd4535629d574\",\"lastSeen\":1471906543798}","timestamp":"2016-08-22T22:55:43.798Z"}
{"level":"info","message":"received FIND_NODE from {\"protocol\":\"0.8.0\",\"address\":\"STORJ-CLUS-020.storj.space\",\"port\":4100,\"nodeID\":\"1a02769ee67b445ea2b0949f049fd4535629d574\",\"lastSeen\":1471768079822}","timestamp":"2016-08-22T22:55:43.828Z"}
{"level":"info","message":"replying to message to 9f92f3342460878533a7fc0324c795c03b43bf82","timestamp":"2016-08-22T22:55:43.828Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"STORJ-CLUS-020.storj.space\",\"port\":4100,\"nodeID\":\"1a02769ee67b445ea2b0949f049fd4535629d574\",\"lastSeen\":1471906589047}","timestamp":"2016-08-22T22:56:29.047Z"}
{"level":"info","message":"received FIND_NODE from {\"protocol\":\"0.8.0\",\"address\":\"STORJ-CLUS-020.storj.space\",\"port\":4100,\"nodeID\":\"1a02769ee67b445ea2b0949f049fd4535629d574\",\"lastSeen\":1471768079822}","timestamp":"2016-08-22T22:56:29.077Z"}
{"level":"info","message":"replying to message to dc3fa1386be9151280ff35413ed58276acb85dea","timestamp":"2016-08-22T22:56:29.078Z"}
{"level":"warn","message":"tunnel connection lost, reason: socket hang up","timestamp":"2016-08-22T22:57:10.054Z"}
{"level":"info","message":"sending OPEN_TUNNEL message to {\"protocol\":\"0.8.0\",\"address\":\"hdd.siblin.ru\",\"port\":55720,\"nodeID\":\"38b4a5724bf57ad6ab053b5ddca5c31a786e0622\",\"lastSeen\":1471906630054}","timestamp":"2016-08-22T22:57:10.055Z"}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:211:15)
    at Socket.socketOnEnd (_http_client.js:303:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

```
And another with the same error
```
{"level":"info","message":"replying to message to 8215656182a2e6f07eaf4c8af23d825f185a5408","timestamp":"2016-08-24T20:43:13.681Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"server014.storj.dk\",\"port\":5114,\"nodeID\":\"52b49d39eee0e179374c6747746ad699f01a1ce2\",\"lastSeen\":1472071395206}","timestamp":"2016-08-24T20:43:15.206Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.8.0\",\"address\":\"server022.storj.dk\",\"port\":5222,\"nodeID\":\"96d578d08e9ccbe781d7c3f62151bf8990b38276\",\"lastSeen\":1472071395233}","timestamp":"2016-08-24T20:43:15.233Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.8.0\",\"address\":\"server025.storj.dk\",\"port\":5925,\"nodeID\":\"49da99a6d6e78bab30092e47cf7e222c92f4d00e\",\"lastSeen\":1472071395254}","timestamp":"2016-08-24T20:43:15.254Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"server022.storj.dk\",\"port\":5222,\"nodeID\":\"96d578d08e9ccbe781d7c3f62151bf8990b38276\",\"lastSeen\":1472071395360}","timestamp":"2016-08-24T20:43:15.360Z"}
{"level":"info","message":"replying to message to a7994a42a9ac1bed01a3fde77a03b0c66c764cec","timestamp":"2016-08-24T20:43:15.385Z"}
{"level":"warn","message":"rpc call 339dd10a9a452849d636bc0198f22ad18eecd8d4 timed out","timestamp":"2016-08-24T20:43:16.998Z"}
{"level":"info","message":"replying to message to c5597b73173fc96af12675073d9d9a5743571e10","timestamp":"2016-08-24T20:43:16.999Z"}
{"level":"warn","message":"rpc call 07dc71e504487a22346abe60245a35930f9e64d6 timed out","timestamp":"2016-08-24T20:43:17.016Z"}
{"level":"warn","message":"RPC with ID `07dc71e504487a22346abe60245a35930f9e64d6` timed out","timestamp":"2016-08-24T20:43:17.017Z"}
{"level":"warn","message":"rpc call b3fb9cecedc818577010f03563d540fcda837e06 timed out","timestamp":"2016-08-24T20:43:17.017Z"}
{"level":"info","message":"replying to message to b3b5be0b9daaaf95c2ef57d4d51903a05e7d53f5","timestamp":"2016-08-24T20:43:17.017Z"}
{"level":"warn","message":"rpc call 5a3a646cefce19d70e4f2aa06257a098971131d3 timed out","timestamp":"2016-08-24T20:43:17.032Z"}
{"level":"info","message":"replying to message to b01ecb4fe772a31ec0baa194dfed88a995829759","timestamp":"2016-08-24T20:43:17.032Z"}
{"level":"warn","message":"tunnel connection lost, reason: socket hang up","timestamp":"2016-08-24T20:43:17.549Z"}
{"level":"info","message":"sending OPEN_TUNNEL message to {\"protocol\":\"0.8.0\",\"address\":\"storj3.sdo-srv.com\",\"port\":4000,\"nodeID\":\"c59b33eec325de62297d3a5fdfbd1bfd53f2e547\",\"lastSeen\":1472071397551}","timestamp":"2016-08-24T20:43:17.551Z"}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:211:15)
    at Socket.socketOnEnd (_http_client.js:303:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. storjshare start

**Comment by brizio1971** [comment]
Same problem to me, but I have:

node --version
v4.4.4

storjshare-0 (out): {"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.8.0\",\"address\":\"104.196.133.105\",\"port\":8447,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1472472226435}","timestamp":"2016-08-29T12:03:46.436Z"}
storjshare-0 (out): {"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"104.196.133.105\",\"port\":8447,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1472472226710}","timestamp":"2016-08-29T12:03:46.710Z"}
storjshare-0 (out): {"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.8.0\",\"address\":\"104.196.133.105\",\"port\":8447,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1472472226733}","timestamp":"2016-08-29T12:03:46.733Z"}
storjshare-0 (out): {"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"104.196.133.105\",\"port\":8447,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1472472227013}","timestamp":"2016-08-29T12:03:47.013Z"}
storjshare-0 (out): {"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.8.0\",\"address\":\"104.196.133.105\",\"port\":8447,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1472472227041}","timestamp":"2016-08-29T12:03:47.041Z"}
storjshare-0 (out): {"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"104.196.133.105\",\"port\":8447,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1472472227512}","timestamp":"2016-08-29T12:03:47.512Z"}
storjshare-0 (out): {"level":"warn","message":"missing or empty reply from contact","timestamp":"2016-08-29T12:05:17.603Z"}
storjshare-0 (out): {"level":"info","message":"publishing message on topic \"0e01\"","timestamp":"2016-08-29T12:07:37.034Z"}
storjshare-0 (out): {"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.8.0\",\"address\":\"104.196.133.105\",\"port\":8447,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1472472457035}","timestamp":"2016-08-29T12:07:37.035Z"}
storjshare-0 (out): {"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"104.196.133.105\",\"port\":8447,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1472472492381}","timestamp":"2016-08-29T12:08:12.381Z"}
storjshare-0 (out): {"type":"info","message":"telemetry report {\"storage\":{\"free\":320901706191,\"used\":1220841009},\"bandwidth\":{\"upload\":16.9,\"download\":90.53},\"contact\":{\"protocol\":\"0.8.0\",\"address\":\"[object Object]\",\"port\":4010,\"nodeID\":\"3dfa5f2be554b8b8688283e892f44dcef2fa6a64\",\"lastSeen\":1472204184808},\"payment\":\"13a8AKRquHtkepAQFbA8wPXNmxa3cwAVJx\"}","timestamp":"2016-08-29T12:08:44.161Z"}

storjshare-0 (err):     at Socket.emit (events.js:166:7)
storjshare-0 (err):     at endReadableNT (_stream_readable.js:913:12)
storjshare-0 (err):     at nextTickCallbackWith2Args (node.js:442:9)
storjshare-0 (err):     at process._tickDomainCallback (node.js:397:17)
storjshare-0 (err): Error: socket hang up
storjshare-0 (err):     at createHangUpError (_http_client.js:200:15)
storjshare-0 (err):     at Socket.socketOnEnd (_http_client.js:292:23)
storjshare-0 (err):     at emitNone (events.js:72:20)
storjshare-0 (err):     at Socket.emit (events.js:166:7)
storjshare-0 (err):     at endReadableNT (_stream_readable.js:913:12)
storjshare-0 (err):     at nextTickCallbackWith2Args (node.js:442:9)
storjshare-0 (err):     at process._tickDomainCallback (node.js:397:17)
storjshare-0 (err): Error: socket hang up
storjshare-0 (err):     at createHangUpError (_http_client.js:200:15)
storjshare-0 (err):     at Socket.socketOnEnd (_http_client.js:292:23)
storjshare-0 (err):     at emitNone (events.js:72:20)
storjshare-0 (err):     at Socket.emit (events.js:166:7)
storjshare-0 (err):     at endReadableNT (_stream_readable.js:913:12)
storjshare-0 (err):     at nextTickCallbackWith2Args (node.js:442:9)
storjshare-0 (err):     at process._tickDomainCallback (node.js:397:17)

**Comment by ramontalvo** [comment]
I have kind of the same issue : I have two machines, first running 1node and the second 3nodes. They used to work fine but now they just get connected peers and no new contracts or more spaced used.

I noticed both getting the same error on the console "Uncaught Error: socket hang up"

One machine is Windows 10 the other is Lubuntu

I'm ruining GUI 2.0.5
Core 3.1.0
Protocol 0.8.0

**Comment by lakewik** [comment]
I using the latest storjshare-cli version. I have same error:
```

> {"level":"info","message":"sending OFFER message to {\"protocol\":\"0.8.0\",\"address\":\"server025.storj.dk\",\"port\":5325,\"nodeID\":\"49da99a6d6e78bab30092e47cf7e222c92f4d00e\",\"lastSeen\":1472677746067}","timestamp":"2016-08-31T21:09:06.067Z"}
> {"level":"debug","message":"queuing callback for reponse to 42df29f0f53095ed52931b03c80b21f327958c43","timestamp":"2016-08-31T21:09:06.076Z"}
> {"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"104.196.163.120\",\"port\":8449,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1472677746258}","timestamp":"2016-08-31T21:09:06.258Z"}
> {"level":"debug","message":"updating contact {\"protocol\":\"0.8.0\",\"address\":\"104.196.163.120\",\"port\":8449,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1472677746258}","timestamp":"2016-08-31T21:09:06.258Z"}
> {"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-08-31T21:09:06.258Z"}
> {"level":"debug","message":"checking pending rpc callback stack for 4668e70231c26289eacdfcabc9a109ef55c714e6","timestamp":"2016-08-31T21:09:06.281Z"}
> {"level":"debug","message":"cleaning bad contacts from routing table","timestamp":"2016-08-31T21:09:09.880Z"}
> {"level":"debug","message":"dropping 0 bad contacts from router","timestamp":"2016-08-31T21:09:09.881Z"}
> {"level":"debug","message":"checking pending rpc callbacks for expirations","timestamp":"2016-08-31T21:09:10.075Z"}
> {"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"91.65.141.16\",\"port\":44967,\"nodeID\":\"9aa01fb29397377e6f5ffef1098bf877701f24be\",\"lastSeen\":1472677750347}","timestamp":"2016-08-31T21:09:10.347Z"}
> {"level":"debug","message":"updating contact {\"protocol\":\"0.8.0\",\"address\":\"91.65.141.16\",\"port\":44967,\"nodeID\":\"9aa01fb29397377e6f5ffef1098bf877701f24be\",\"lastSeen\":1472677750347}","timestamp":"2016-08-31T21:09:10.347Z"}
> {"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-08-31T21:09:10.347Z"}
> {"level":"debug","message":"checking pending rpc callback stack for 2d2338ed53311ea44a83b1d5707b42764386222b","timestamp":"2016-08-31T21:09:10.365Z"}
> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: socket hang up
>     at createHangUpError (_http_client.js:200:15)
>     at Socket.socketOnEnd (_http_client.js:292:23)
>     at emitNone (events.js:72:20)
>     at Socket.emit (events.js:166:7)
>     at endReadableNT (_stream_readable.js:913:12)
>     at nextTickCallbackWith2Args (node.js:442:9)
>     at process._tickCallback (node.js:356:17)

```

**Comment by brizio1971** [comment]
Problem still present to me:

storjshare --version.

StorjShare: 6.0.2
Core:       3.1.0
Protocol:   0.8.0

node --version.

v4.5.0


storjshare-0 (out): {"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.8.0\",\"address\":\"88.198.21.198\",\"port\":6000,\"nodeID\":\"2fb81016e8309ee979da330330357d4a43a58dad\",\"lastSeen\":1472716670394}","timestamp":"2016-09-01T07:57:50.394Z"}
storjshare-0 (out): {"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"88.198.21.198\",\"port\":6000,\"nodeID\":\"2fb81016e8309ee979da330330357d4a43a58dad\",\"lastSeen\":1472716670530}","timestamp":"2016-09-01T07:57:50.530Z"}
storjshare-0 (out): {"level":"info","message":"replying to message to 4db784a2413224bfc7093324e27994577f7980df","timestamp":"2016-09-01T07:57:50.551Z"}
storjshare-0 (out): {"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.8.0\",\"address\":\"88.198.21.198\",\"port\":6000,\"nodeID\":\"2fb81016e8309ee979da330330357d4a43a58dad\",\"lastSeen\":1472716670592}","timestamp":"2016-09-01T07:57:50.592Z"}
storjshare-0 (out): {"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.8.0\",\"address\":\"104.196.163.120\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1472716670603}","timestamp":"2016-09-01T07:57:50.603Z"}
storjshare-0 (out): {"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.8.0\",\"address\":\"chapo.c.orequi.site\",\"port\":4000,\"nodeID\":\"cc6d63e3328c104d264068d08f89cf6b29ba95f7\",\"lastSeen\":1472716670614}","timestamp":"2016-09-01T07:57:50.614Z"}
storjshare-0 (out): {"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"88.198.21.198\",\"port\":6000,\"nodeID\":\"2fb81016e8309ee979da330330357d4a43a58dad\",\"lastSeen\":1472716670719}","timestamp":"2016-09-01T07:57:50.719Z"}
storjshare-0 (out): {"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"104.196.163.120\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1472716670893}","timestamp":"2016-09-01T07:57:50.893Z"}
storjshare-0 (out): {"level":"info","message":"received valid message from {\"protocol\":\"0.8.0\",\"address\":\"chapo.c.orequi.site\",\"port\":4000,\"nodeID\":\"cc6d63e3328c104d264068d08f89cf6b29ba95f7\",\"lastSeen\":1472716670928}","timestamp":"2016-09-01T07:57:50.928Z"}
storjshare-0 (out): {"level":"warn","message":"could not locate renter for offer","timestamp":"2016-09-01T07:57:50.949Z"}
storjshare-0 (out): {"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-09-01T07:58:25.694Z"}
storjshare-0 (out): {"level":"warn","message":"you are not publicly reachable, trying traversal strategies...","timestamp":"2016-09-01T07:58:25.731Z"}
storjshare-0 (out): {"type":"info","message":"telemetry report {\"storage\":{\"free\":318762021861,\"used\":3360525339},\"bandwidth\":{\"upload\":16.81,\"download\":83.11},\"contact\":{\"protocol\":\"0.8.0\",\"address\":\"10.1.0.71\",\"port\":4010,\"nodeID\":\"d3c8f54a099e0606cd5f69848c9da313d688ee99\",\"lastSeen\":1472716705677},\"payment\":\"13a8AKRquHtkepAQFbA8wPXNmxa3cwAVJx\"}","timestamp":"2016-09-01T07:58:25.804Z"}
storjshare-0 (out): {"level":"warn","message":"UPnP device has no public IP address: 192.168.10.254","timestamp":"2016-09-01T07:58:26.131Z"}
storjshare-0 (out): {"level":"info","message":"node created with nodeID d3c8f54a099e0606cd5f69848c9da313d688ee99","timestamp":"2016-09-01T07:58:26.150Z"}
storjshare-0 (out): {"level":"warn","message":"UPnP device has no public IP address: 192.168.10.254","timestamp":"2016-09-01T07:58:26.154Z"}
storjshare-0 (out): {"level":"warn","message":"failed to map port for tunserver: UPnP device has no public IP address","timestamp":"2016-09-01T07:58:26.154Z"}
storjshare-0 (out): {"level":"info","message":"clock is synchronized with ntp, delta: 1391","timestamp":"2016-09-01T07:58:26.207Z"}
storjshare-0 (out): {"level":"info","message":"requesting probe from nearest neighbor","timestamp":"2016-09-01T07:58:26.830Z"}
storjshare-0 (out): {"level":"info","message":"sending PROBE message to {\"protocol\":\"0.8.0\",\"address\":\"104.196.133.105\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1472716706832}","timestamp":"2016-09-01T07:58:26.832Z"}

storjshare-0 (err):     at Socket.emit (events.js:166:7)
storjshare-0 (err):     at endReadableNT (_stream_readable.js:921:12)
storjshare-0 (err):     at nextTickCallbackWith2Args (node.js:442:9)
storjshare-0 (err):     at process._tickDomainCallback (node.js:397:17)
storjshare-0 (err): Error: socket hang up
storjshare-0 (err):     at createHangUpError (_http_client.js:213:15)
storjshare-0 (err):     at Socket.socketOnEnd (_http_client.js:305:23)
storjshare-0 (err):     at emitNone (events.js:72:20)
storjshare-0 (err):     at Socket.emit (events.js:166:7)
storjshare-0 (err):     at endReadableNT (_stream_readable.js:921:12)
storjshare-0 (err):     at nextTickCallbackWith2Args (node.js:442:9)
storjshare-0 (err):     at process._tickDomainCallback (node.js:397:17)
storjshare-0 (err): Error: socket hang up
storjshare-0 (err):     at createHangUpError (_http_client.js:213:15)
storjshare-0 (err):     at Socket.socketOnEnd (_http_client.js:305:23)
storjshare-0 (err):     at emitNone (events.js:72:20)
storjshare-0 (err):     at Socket.emit (events.js:166:7)
storjshare-0 (err):     at endReadableNT (_stream_readable.js:921:12)
storjshare-0 (err):     at nextTickCallbackWith2Args (node.js:442:9)
storjshare-0 (err):     at process._tickDomainCallback (node.js:397:17)

**Comment by davidak** [comment]
Still same problem:

```
{"level":"error","message":"failed to handle message, reason: Unexpected token <","timestamp":"2016-09-02T22:28:06.212Z"}
{"level":"error","message":"failed to handle message, reason: Unexpected token <","timestamp":"2016-09-02T22:31:06.916Z"}
{"level":"error","message":"failed to handle message, reason: Unexpected token <","timestamp":"2016-09-02T22:41:55.908Z"}
{"level":"error","message":"Protocol version is incompatible","timestamp":"2016-09-02T22:50:50.872Z"}
{"level":"error","message":"Protocol version is incompatible","timestamp":"2016-09-02T22:51:51.067Z"}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:211:15)
    at Socket.socketOnEnd (_http_client.js:303:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

---

StorjShare: 6.0.2
Core:       3.1.0
Protocol:   0.8.0
Node: v4.4.5

**Comment by bookchin** [comment]
Fixed here https://github.com/kadtools/kad/releases/tag/v1.5.18

**Comment by brizio1971** [comment]
Hello, I have upgrade to last release using:
npm install kad
kad@1.5.18 node_modules/kad
├── ms@0.7.1
├── merge@1.2.0
├── hat@0.0.3
├── async@0.9.2
├── colors@1.1.2
├── kad-localstorage@0.0.7 (dom-storage@2.0.2)
├── kad-memstore@0.0.1 (readable-stream@2.1.5)
├── kad-fs@0.0.4 (readable-stream@2.1.5)
├── lodash@3.10.1
└── clarinet@0.11.0

but I still get the error : 

storjshare-0 Error: socket hang up
storjshare-0     at createHangUpError (_http_client.js:200:15)
storjshare-0     at Socket.socketOnEnd (_http_client.js:292:23)
storjshare-0     at emitNone (events.js:72:20)
storjshare-0     at Socket.emit (events.js:166:7)
storjshare-0     at endReadableNT (_stream_readable.js:913:12)
storjshare-0     at nextTickCallbackWith2Args (node.js:442:9)
storjshare-0     at process._tickDomainCallback (node.js:397:17)

**Comment by lakewik** [comment]
Still same error:

> `"level":"debug","message":"checking pending rpc callback stack for 1c55c9d59544e246691f2a110ecfff13163186fa","timestamp":"2016-10-11T18:54:12.949Z"}
{"level":"warn","message":"tunnel connection lost, reason: socket hang up","timestamp":"2016-10-11T18:54:12.953Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"4.0.0\",\"protocol\":\"0.9.0\",\"address\":\"server014.storj.dk\",\"port\":5009,\"nodeID\":\"a69d4f2e3e97e4f26ece3d437b2825c5d7fed9e6\",\"lastSeen\":1476212054432}","timestamp":"2016-10-11T18:54:14.432Z"}
{"level":"debug","message":"updating contact {\"userAgent\":\"4.0.0\",\"protocol\":\"0.9.0\",\"address\":\"server014.storj.dk\",\"port\":5009,\"nodeID\":\"a69d4f2e3e97e4f26ece3d437b2825c5d7fed9e6\",\"lastSeen\":1476212054432}","timestamp":"2016-10-11T18:54:14.432Z"}
{"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-10-11T18:54:14.432Z"}
{"level":"debug","message":"checking pending rpc callback stack for b12d26598b73e09fb2b8873c100f7bf693b6a6da","timestamp":"2016-10-11T18:54:14.458Z"}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:200:15)
    at Socket.socketOnEnd (_http_client.js:292:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)`

**Comment by bookchin** [comment]
-.-

**Comment by bookchin** [comment]
Fixed in latest storj-lib
